### ISSUE TITLE
jq not working on ARM

### ISSUE THREAD

**Issue by amwill04** [CircleCI-Public/arm-preview-docs#8]
Using the `arm` with the following

```yaml
  deploy:
    machine:
      image: ubuntu-2204:2022.07.1
    resource_class: arm.medium
    steps:
        - run:
            command: jq
```

returns the following:
```
-bash: /usr/local/bin/jq: cannot execute binary file: Exec format error
```

Seems the preinstalled `jq` is not for ARM

Removing `/usr/local/bin/jq` and reinstalling with `sudo apt-get install jq` solves the issues as it installs the `arm` build (i am assuming). Does mean that `jq` commands need to be rewritten as `/usr/bin/jq ...` however.

**Comment by FelicianoTech** [comment]
Looking into this.

**Comment by amwill04** [comment]
Thanks @felicianotech 

My "fix" is the following anyways

```yaml
      - run:
          name: fix jq for ARM
          command: |
            sudo rm /usr/local/bin/jq
            sudo apt-get install jq
            sudo mv /usr/bin/jq /usr/local/bin/jq
```
